#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'

  require "lexer"
  require "nodes"

class Parser < Racc::Parser

module_eval(<<'...end grammar.y/module_eval...', 'grammar.y', 227)
  def parse(code, show_tokens=false)
    @tokens = Lexer.new.tokenize(code) # Tokenize the code using our lexer
    puts @tokens.inspect if show_tokens
    do_parse # Kickoff the parsing process
  end
  
  def next_token
    @tokens.shift
  end
...end grammar.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    29,    30,    27,    28,    17,    19,    20,    21,    22,    23,
    24,    26,    85,    33,    84,    25,    29,    30,    27,    28,
    17,    19,    20,    21,    22,    23,    24,    26,    33,    77,
    16,    25,    18,    58,    29,    30,    27,    28,    56,    19,
    20,    21,    22,    23,    24,    26,    16,    79,    18,    25,
    53,    29,    30,    27,    28,    52,    19,    20,    21,    22,
    23,    24,    26,    88,    16,    73,    25,    29,    30,    27,
    28,    51,    19,    20,    21,    22,    23,    24,    26,    31,
    77,    16,    25,    29,    30,    27,    28,    77,    19,    20,
    21,    22,    23,    24,    26,    48,    94,    16,    25,    29,
    30,    27,    28,    33,    19,    20,    21,    22,    23,    24,
    26,   nil,   nil,    16,    25,    29,    30,    27,    28,   nil,
    19,    20,    21,    22,    23,    24,    26,   nil,   nil,    16,
    25,    29,    30,    27,    28,   nil,    19,    20,    21,    22,
    23,    24,    26,   nil,   nil,    16,    25,    29,    30,    27,
    28,   nil,    19,    20,    21,    22,    23,    24,    26,   nil,
   nil,    16,    25,    29,    30,    27,    28,   nil,    19,    20,
    21,    22,    23,    24,    26,   nil,   nil,    16,    25,    29,
    30,    27,    28,   nil,    19,    20,    21,    22,    23,    24,
    26,   nil,   nil,    16,    25,    29,    30,    27,    28,   nil,
    19,    20,    21,    22,    23,    24,    26,   nil,   nil,    16,
    25,    29,    30,    27,    28,   nil,    19,    20,    21,    22,
    23,    24,    26,   nil,   nil,    16,    25,    29,    30,    27,
    28,   nil,    19,    20,    21,    22,    23,    24,    26,   nil,
   nil,    16,    25,    29,    30,    27,    28,   nil,    19,    20,
    21,    22,    23,    24,    26,   nil,   nil,    16,    25,    29,
    30,    27,    28,   nil,    19,    20,    21,    22,    23,    24,
    26,   nil,   nil,    16,    25,    29,    30,    27,    28,   nil,
    19,    20,    21,    22,    23,    24,    26,   nil,   nil,    16,
    25,    29,    30,    27,    28,   nil,    19,    20,    21,    22,
    23,    24,    26,   nil,   nil,    16,    25,    29,    30,    27,
    28,   nil,    19,    20,    21,    22,    23,    24,    26,   nil,
   nil,    16,    25,    29,    30,    27,    28,   nil,    19,    20,
    21,    22,    23,    24,    26,   nil,   nil,    16,    25,    29,
    30,    27,    28,    17,    19,    20,    21,    22,    23,    24,
    26,    17,    90,    16,    25,    29,    30,    27,    28,   nil,
    19,    20,    21,    22,    23,    24,    26,   nil,   nil,    16,
    25,    18,    33,   nil,    44,    45,    42,    43,    33,    18,
    44,    45,    42,    43,    33,    16,    44,    45,    42,    43,
    38,    39,    40,    41,    36,    37,    35,    34,    77,   nil,
    33,    71,    44,    45,    42,    43,    38,    39,    40,    41,
    36,    37,    35,    34,    77,    49,    33,    48,    44,    45,
    42,    43,    38,    39,    40,    41,    36,    37,    35,    34,
    33,   nil,    44,    45,    42,    43,    38,    39,    40,    41,
    36,    37,    35,    34,    33,   nil,    44,    45,    42,    43,
    38,    39,    40,    41,    36,    37,    35,    34,    33,   nil,
    44,    45,    42,    43,    38,    39,    40,    41,    36,    37,
    35,    34,    33,   nil,    44,    45,    42,    43,    38,    39,
    40,    41,    36,    37,    35,    34,    33,   nil,    44,    45,
    42,    43,    38,    39,    40,    41,    36,    37,    35,    34,
    33,   nil,    44,    45,    42,    43,    38,    39,    40,    41,
    36,    37,    35,    34,    33,   nil,    44,    45,    42,    43,
    38,    39,    40,    41,    36,    37,    35,    33,   nil,    44,
    45,    42,    43,    38,    39,    40,    41,    36,    37,    33,
   nil,    44,    45,    42,    43,    38,    39,    40,    41,    33,
   nil,    44,    45,    42,    43,    38,    39,    40,    41,    33,
   nil,    44,    45,    42,    43,    33,   nil,    44,    45,    42,
    43,    33,   nil,    44,    45,    33,   nil,    44,    45,    92,
   nil,    91 ]

racc_action_check = [
    77,    77,    77,    77,    77,    77,    77,    77,    77,    77,
    77,    77,    74,    69,    74,    77,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,    70,    52,
    77,     0,    77,    33,    48,    48,    48,    48,    31,    48,
    48,    48,    48,    48,    48,    48,     0,    52,     0,    48,
    28,    16,    16,    16,    16,    27,    16,    16,    16,    16,
    16,    16,    16,    79,    48,    48,    16,    49,    49,    49,
    49,    26,    49,    49,    49,    49,    49,    49,    49,     1,
    91,    16,    49,    25,    25,    25,    25,    53,    25,    25,
    25,    25,    25,    25,    25,    58,    92,    49,    25,    85,
    85,    85,    85,    50,    85,    85,    85,    85,    85,    85,
    85,   nil,   nil,    25,    85,    29,    29,    29,    29,   nil,
    29,    29,    29,    29,    29,    29,    29,   nil,   nil,    85,
    29,    30,    30,    30,    30,   nil,    30,    30,    30,    30,
    30,    30,    30,   nil,   nil,    29,    30,    45,    45,    45,
    45,   nil,    45,    45,    45,    45,    45,    45,    45,   nil,
   nil,    30,    45,    32,    32,    32,    32,   nil,    32,    32,
    32,    32,    32,    32,    32,   nil,   nil,    45,    32,    44,
    44,    44,    44,   nil,    44,    44,    44,    44,    44,    44,
    44,   nil,   nil,    32,    44,    34,    34,    34,    34,   nil,
    34,    34,    34,    34,    34,    34,    34,   nil,   nil,    44,
    34,    35,    35,    35,    35,   nil,    35,    35,    35,    35,
    35,    35,    35,   nil,   nil,    34,    35,    36,    36,    36,
    36,   nil,    36,    36,    36,    36,    36,    36,    36,   nil,
   nil,    35,    36,    37,    37,    37,    37,   nil,    37,    37,
    37,    37,    37,    37,    37,   nil,   nil,    36,    37,    38,
    38,    38,    38,   nil,    38,    38,    38,    38,    38,    38,
    38,   nil,   nil,    37,    38,    39,    39,    39,    39,   nil,
    39,    39,    39,    39,    39,    39,    39,   nil,   nil,    38,
    39,    40,    40,    40,    40,   nil,    40,    40,    40,    40,
    40,    40,    40,   nil,   nil,    39,    40,    42,    42,    42,
    42,   nil,    42,    42,    42,    42,    42,    42,    42,   nil,
   nil,    40,    42,    41,    41,    41,    41,   nil,    41,    41,
    41,    41,    41,    41,    41,   nil,   nil,    42,    41,    43,
    43,    43,    43,    86,    43,    43,    43,    43,    43,    43,
    43,     2,    86,    41,    43,    51,    51,    51,    51,   nil,
    51,    51,    51,    51,    51,    51,    51,   nil,   nil,    43,
    51,    86,    66,   nil,    66,    66,    66,    66,    63,     2,
    63,    63,    63,    63,    46,    51,    46,    46,    46,    46,
    46,    46,    46,    46,    46,    46,    46,    46,    55,   nil,
    55,    46,    55,    55,    55,    55,    55,    55,    55,    55,
    55,    55,    55,    55,    54,    24,    54,    24,    54,    54,
    54,    54,    54,    54,    54,    54,    54,    54,    54,    54,
    89,   nil,    89,    89,    89,    89,    89,    89,    89,    89,
    89,    89,    89,    89,    72,   nil,    72,    72,    72,    72,
    72,    72,    72,    72,    72,    72,    72,    72,    75,   nil,
    75,    75,    75,    75,    75,    75,    75,    75,    75,    75,
    75,    75,    76,   nil,    76,    76,    76,    76,    76,    76,
    76,    76,    76,    76,    76,    76,     3,   nil,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
    57,   nil,    57,    57,    57,    57,    57,    57,    57,    57,
    57,    57,    57,    57,    59,   nil,    59,    59,    59,    59,
    59,    59,    59,    59,    59,    59,    59,    60,   nil,    60,
    60,    60,    60,    60,    60,    60,    60,    60,    60,    61,
   nil,    61,    61,    61,    61,    61,    61,    61,    61,    62,
   nil,    62,    62,    62,    62,    62,    62,    62,    62,    65,
   nil,    65,    65,    65,    65,    64,   nil,    64,    64,    64,
    64,    68,   nil,    68,    68,    67,   nil,    67,    67,    87,
   nil,    87 ]

racc_action_pointer = [
    14,    79,   345,   470,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    49,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   385,    81,    41,    43,    37,   113,
   129,    38,   161,    21,   193,   209,   225,   241,   257,   273,
   289,   321,   305,   337,   177,   145,   368,   nil,    32,    65,
    87,   353,    15,    73,   400,   384,   nil,   484,    63,   498,
   511,   523,   533,   362,   549,   543,   356,   559,   555,    -3,
    12,   nil,   428,   nil,   -19,   442,   456,    -2,   nil,    51,
   nil,   nil,   nil,   nil,   nil,    97,   337,   548,   nil,   414,
   nil,    66,    84,   nil,   nil ]

racc_action_default = [
    -1,   -59,    -2,    -3,    -6,    -7,    -8,    -9,   -10,   -11,
   -12,   -13,   -14,   -15,   -16,   -17,   -59,   -19,   -20,   -21,
   -22,   -23,   -24,   -25,   -48,   -59,   -46,   -59,   -59,   -59,
   -59,   -59,    -5,   -59,   -59,   -59,   -59,   -59,   -59,   -59,
   -59,   -59,   -59,   -59,   -59,   -59,   -59,   -26,   -59,   -59,
   -45,   -59,   -59,   -59,   -59,   -59,    95,    -4,   -28,   -33,
   -34,   -35,   -36,   -37,   -38,   -39,   -40,   -41,   -42,   -43,
   -44,   -18,   -31,   -29,   -59,   -49,   -47,   -59,   -51,   -53,
   -56,   -57,   -58,   -27,   -30,   -59,   -59,   -59,   -54,   -32,
   -50,   -59,   -59,   -52,   -55 ]

racc_goto_table = [
    32,     2,    46,    78,    80,    81,    82,    47,    87,    74,
     1,    50,   nil,   nil,   nil,    54,    55,   nil,    57,   nil,
    59,    60,    61,    62,    63,    64,    65,    66,    67,    68,
    69,    70,   nil,   nil,    72,    75,   nil,    76,   nil,   nil,
   nil,    83,    93,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    89,   nil,   nil,   nil,   nil,   nil,   nil,    86,   nil,
   nil,   nil,   nil,   nil,    32 ]

racc_goto_check = [
     4,     2,     3,    18,    18,    18,    18,    16,    19,    17,
     1,     3,   nil,   nil,   nil,     3,     3,   nil,     3,   nil,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,   nil,   nil,     3,     3,   nil,     3,   nil,   nil,
   nil,    16,    18,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     3,   nil,   nil,   nil,   nil,   nil,   nil,     2,   nil,
   nil,   nil,   nil,   nil,     4 ]

racc_goto_pointer = [
   nil,    10,     1,   -14,    -2,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   -17,   -39,   -49,   -71 ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     5,     6,     7,     8,     9,
    10,    11,    12,    13,    14,    15,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 36, :_reduce_1,
  1, 36, :_reduce_2,
  1, 37, :_reduce_3,
  3, 37, :_reduce_4,
  2, 37, :_reduce_5,
  1, 37, :_reduce_6,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  3, 38, :_reduce_18,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 40, :_reduce_21,
  1, 40, :_reduce_22,
  1, 40, :_reduce_23,
  1, 40, :_reduce_24,
  1, 40, :_reduce_25,
  2, 41, :_reduce_26,
  4, 41, :_reduce_27,
  3, 41, :_reduce_28,
  2, 51, :_reduce_29,
  3, 51, :_reduce_30,
  1, 52, :_reduce_31,
  3, 52, :_reduce_32,
  3, 42, :_reduce_33,
  3, 42, :_reduce_34,
  3, 42, :_reduce_35,
  3, 42, :_reduce_36,
  3, 42, :_reduce_37,
  3, 42, :_reduce_38,
  3, 42, :_reduce_39,
  3, 42, :_reduce_40,
  3, 42, :_reduce_41,
  3, 42, :_reduce_42,
  3, 42, :_reduce_43,
  3, 42, :_reduce_44,
  2, 42, :_reduce_45,
  1, 43, :_reduce_46,
  3, 44, :_reduce_47,
  1, 45, :_reduce_48,
  3, 46, :_reduce_49,
  3, 53, :_reduce_50,
  3, 47, :_reduce_51,
  6, 47, :_reduce_52,
  0, 54, :_reduce_53,
  1, 54, :_reduce_54,
  3, 54, :_reduce_55,
  3, 48, :_reduce_56,
  3, 49, :_reduce_57,
  3, 50, :_reduce_58 ]

racc_reduce_n = 59

racc_shift_n = 95

racc_token_table = {
  false => 0,
  :error => 1,
  :IF => 2,
  :WHILE => 3,
  :DEF => 4,
  :CLASS => 5,
  :NEWLINE => 6,
  :NUMBER => 7,
  :STRING => 8,
  :TRUE => 9,
  :FALSE => 10,
  :NIL => 11,
  :IDENTIFIER => 12,
  :CONSTANT => 13,
  :INDENT => 14,
  :DEDENT => 15,
  "." => 16,
  "!" => 17,
  "*" => 18,
  "/" => 19,
  "+" => 20,
  "-" => 21,
  ">" => 22,
  ">=" => 23,
  "<" => 24,
  "<=" => 25,
  "==" => 26,
  "!=" => 27,
  "&&" => 28,
  "||" => 29,
  "=" => 30,
  "," => 31,
  "(" => 32,
  ")" => 33,
  ";" => 34 }

racc_nt_base = 35

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "IF",
  "WHILE",
  "DEF",
  "CLASS",
  "NEWLINE",
  "NUMBER",
  "STRING",
  "TRUE",
  "FALSE",
  "NIL",
  "IDENTIFIER",
  "CONSTANT",
  "INDENT",
  "DEDENT",
  "\".\"",
  "\"!\"",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "\">\"",
  "\">=\"",
  "\"<\"",
  "\"<=\"",
  "\"==\"",
  "\"!=\"",
  "\"&&\"",
  "\"||\"",
  "\"=\"",
  "\",\"",
  "\"(\"",
  "\")\"",
  "\";\"",
  "$start",
  "Program",
  "Expressions",
  "Expression",
  "Terminator",
  "Literal",
  "Call",
  "Operator",
  "GetConstant",
  "SetConstant",
  "GetLocal",
  "SetLocal",
  "Def",
  "Class",
  "If",
  "While",
  "Arguments",
  "ArgList",
  "Block",
  "ParamList" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'grammar.y', 50)
  def _reduce_1(val, _values, result)
     result = Nodes.new([]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 51)
  def _reduce_2(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 68)
  def _reduce_3(val, _values, result)
     result = Nodes.new(val) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 69)
  def _reduce_4(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 70)
  def _reduce_5(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 71)
  def _reduce_6(val, _values, result)
     result = Nodes.new([]) 
    result
  end
.,.,

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

module_eval(<<'.,.,', 'grammar.y', 87)
  def _reduce_18(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 19 omitted

# reduce 20 omitted

module_eval(<<'.,.,', 'grammar.y', 105)
  def _reduce_21(val, _values, result)
     result = NumberNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 106)
  def _reduce_22(val, _values, result)
     result = StringNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 107)
  def _reduce_23(val, _values, result)
     result = TrueNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 108)
  def _reduce_24(val, _values, result)
     result = FalseNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 109)
  def _reduce_25(val, _values, result)
     result = NilNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 121)
  def _reduce_26(val, _values, result)
     result = CallNode.new(nil, val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 123)
  def _reduce_27(val, _values, result)
     result = CallNode.new(val[0], val[2], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 124)
  def _reduce_28(val, _values, result)
     result = CallNode.new(val[0], val[2], []) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 128)
  def _reduce_29(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 129)
  def _reduce_30(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 133)
  def _reduce_31(val, _values, result)
     result = val 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 134)
  def _reduce_32(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 145)
  def _reduce_33(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 146)
  def _reduce_34(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 147)
  def _reduce_35(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 148)
  def _reduce_36(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 149)
  def _reduce_37(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 150)
  def _reduce_38(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 151)
  def _reduce_39(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 152)
  def _reduce_40(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 153)
  def _reduce_41(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 154)
  def _reduce_42(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 155)
  def _reduce_43(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 156)
  def _reduce_44(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 157)
  def _reduce_45(val, _values, result)
     result = CallNode.new(val[1], val[0], []) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 162)
  def _reduce_46(val, _values, result)
     result = GetConstantNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 166)
  def _reduce_47(val, _values, result)
     result = SetConstantNode.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 170)
  def _reduce_48(val, _values, result)
     result = GetLocalNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 174)
  def _reduce_49(val, _values, result)
     result = SetLocalNode.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 186)
  def _reduce_50(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 192)
  def _reduce_51(val, _values, result)
     result = DefNode.new(val[1], [], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 194)
  def _reduce_52(val, _values, result)
     result = DefNode.new(val[1], val[3], val[5]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 198)
  def _reduce_53(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 199)
  def _reduce_54(val, _values, result)
     result = val 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 200)
  def _reduce_55(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 206)
  def _reduce_56(val, _values, result)
     result = ClassNode.new(val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 211)
  def _reduce_57(val, _values, result)
     result = IfNode.new(val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 215)
  def _reduce_58(val, _values, result)
     result = WhileNode.new(val[1], val[2]) 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser
